# Generated by Django 2.0.6 on 2018-06-25 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='summary',
        ),
        migrations.AddField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_body',
            field=models.TextField(blank=True, default='your text'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='your text', max_length=300),
        ),
    ]
