# Generated by Django 2.0.6 on 2018-06-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180625_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='text_body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
