# Generated by Django 2.0.6 on 2018-06-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
